name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
          submodules: recursive
     - name: Build App
       run: |
            chmod +x walls
            ./walls
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git lfs track "**/*"
            git add .
            git commit -m "Built App"
            git push
